services:
  db:
      container_name: ai-drink-db
      image: postgres
      restart: always
      ports:
        - 5433:5432
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: ai-drink-db
      volumes:
        - pgdata:/var/lib/postgresql/data
  adminer:
      depends_on:
        - db
      image: adminer
      restart: always
      ports:
        - 8090:8080

volumes:
  pgdata:
    driver: local