server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ai-drink-db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

application:
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E645267556B58703272357538782F413F4428472B4B6250655368566D5971337436763979244226452948404D635166546A576E
      expiration-time: 78600
